### ISSUE TITLE
Cars and Houses

### ISSUE THREAD

**Issue by suprfrye** [hoathenguyen85/hoathenguyen85.github.io#1]
Hoa, don't fret, you're back on track it seems. I am just now finishing up Week 3, so at least you're not last. 
Great sections. The car analogy to describe arrays is fantastic! The house analogy doesn't seem to work as well for hashes because of their fixed location and ordinal numbering, houses that is. I know you were probably in a hurry to get this section done, but a one look over can help with the minor spelling and grammar mishaps.

**Comment by hoathenguyen85** [comment]
Oh wow!  Didn't think anybody was going to actually read my blog!  I need to be proactive myself and do this too!

Thanks for your encouraging words!  And yeah, I'll make sure to re-read what I wrote to fix those spelling and grammar issues.  xD  Being in a rush is no excuse for silly mistakes, just gotta calm myself down and make sure everything is good!

THANKS!
